fixes

diff --git a/deployment/puppet/contrail/files/zookeeper b/deployment/puppet/contrail/files/zookeeper
--- a/deployment/puppet/contrail/files/zookeeper
+++ b/deployment/puppet/contrail/files/zookeeper
@@ -15,70 +15,162 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-#
-# ZooKeeper
-#
-# chkconfig: 2345 89 9
-# description: zookeeper
+# chkconfig: 2345 85 15
+# description: Summary: ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services. All of these kinds of services are used in some form or another by distributed applications. Each time they are implemented there is a lot of work that goes into fixing the bugs and race conditions that are inevitable. Because of the difficulty of implementing these kinds of services, applications initially usually skimp on them ,which make them brittle in the presence of change and difficult to manage. Even when done correctly, different implementations of these services lead to management complexity when the applications are deployed.
+# processname: java
+# pidfile: /var/run/zookeeper/zookeeper-server.pid
+### BEGIN INIT INFO
+# Provides:          zookeeper-server
+# Required-Start:    $network $local_fs
+# Required-Stop:
+# Should-Start:      $named
+# Should-Stop:
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.
+### END INIT INFO
+set -e
 
-source /etc/rc.d/init.d/functions
-source /usr/libexec/zkEnv.sh
+# Autodetect JAVA_HOME if not defined
+if [ -e /usr/libexec/bigtop-detect-javahome ]; then
+  . /usr/libexec/bigtop-detect-javahome
+elif [ -e /usr/lib/bigtop-utils/bigtop-detect-javahome ]; then
+  . /usr/lib/bigtop-utils/bigtop-detect-javahome
+fi
 
-RETVAL=0
-PIDFILE=/var/lib/zookeeper/data/zookeeper_server.pid
-desc="ZooKeeper daemon"
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON_SCRIPT="/usr/bin/zookeeper-server"
+
+NAME=zookeeper-server
+DESC="ZooKeeper daemon"
+PID_FILE=/var/run/zookeeper/zookeeper-server.pid
+install -d -m 0755 -o zookeeper -g zookeeper /var/run/zookeeper/
+
+DODTIME=3
+
+
+# Checks if the given pid represents a live process.
+# Returns 0 if the pid is a live process, 1 otherwise
+hadoop_is_process_alive() {
+  local pid="$1" 
+  ps -fp $pid | grep $pid | grep zookeeper > /dev/null 2>&1
+}
+
+hadoop_check_pidfile() {
+    local pidfile="$1" # IN
+    local pid
+
+    pid=`cat "$pidfile" 2>/dev/null`
+    if [ "$pid" = '' ]; then
+    # The file probably does not exist or is empty. 
+  return 1
+    fi
+    
+    set -- $pid
+    pid="$1"
+
+    hadoop_is_process_alive $pid
+}
+
+hadoop_process_kill() {
+    local pid="$1"    # IN
+    local signal="$2" # IN
+    local second
+
+    kill -$signal $pid 2>/dev/null
+
+   # Wait a bit to see if the dirty job has really been done
+    for second in 0 1 2 3 4 5 6 7 8 9 10; do
+  if hadoop_is_process_alive "$pid"; then
+         # Success
+      return 0
+  fi
+
+  sleep 1
+    done
+
+   # Timeout
+    return 1
+}
+hadoop_stop_pidfile() {
+    local pidfile="$1" # IN
+    local pid
+
+    pid=`cat "$pidfile" 2>/dev/null`
+    if [ "$pid" = '' ]; then
+      # The file probably does not exist or is empty. Success
+  return 0
+    fi
+    
+    set -- $pid
+    pid="$1"
+
+   # First try the easy way
+    if hadoop_process_kill "$pid" 15; then
+  return 0
+    fi
+
+   # Otherwise try the hard way
+    if hadoop_process_kill "$pid" 9; then
+  return 0
+    fi
+
+    return 1
+}
+
 
 start() {
-  echo -n $"Starting $desc (zookeeper): "
-  daemon --user zookeeper zkServer.sh start
-  RETVAL=$?
-  echo
-  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/zookeeper
-  return $RETVAL
+    su -s /bin/sh zookeeper -c "${DAEMON_SCRIPT} start"
 }
-
 stop() {
-  echo -n $"Stopping $desc (zookeeper): "
-  daemon --user zookeeper zkServer.sh stop
-  RETVAL=$?
-  sleep 5
-  echo
-  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/zookeeper $PIDFILE
-}
-
-restart() {
-  stop
-  start
-}
-
-checkstatus(){
-  status -p $PIDFILE ${JAVA_HOME}/bin/java
-  RETVAL=$?
-}
-
-condrestart(){
-  [ -e /var/lock/subsys/zookeeper ] && restart || :
+  if hadoop_check_pidfile $PID_FILE ;  then
+        su -s /bin/sh zookeeper -c "${DAEMON_SCRIPT} stop"
+  fi
 }
 
 case "$1" in
-  start)
-    start
-    ;;
-  stop)
-    stop
-    ;;
-  status)
-    checkstatus
-    ;;
-  restart)
-    restart
-    ;;
-  condrestart)
-    condrestart
-    ;;
-  *)
-    echo $"Usage: $0 {start|stop|status|restart|condrestart}"
-    exit 1
+    start)
+  start
+  ;;
+    stop)
+  stop 
+  ;;
+    force-stop)
+        echo -n "Forcefully stopping $DESC: "
+        hadoop_stop_pidfile $PID_FILE
+        if hadoop_check_pidfile $PID_FILE ; then
+            echo "$NAME."
+        else
+            echo " ERROR."
+        fi
+  ;;
+    force-reload|condrestart|try-restart)
+  # check wether $DAEMON is running. If so, restart
+        hadoop_check_pidfile $PID_FILE && $0 restart
+  ;;
+    restart|reload)
+        echo -n "Restarting $DESC: "
+        stop
+        [ -n "$DODTIME" ] && sleep $DODTIME
+        $0 start
+  ;;
+    status)
+  echo -n "$NAME is "
+  if hadoop_check_pidfile $PID_FILE ;  then
+      echo "running"
+  else
+      echo "not running."
+      exit 1
+  fi
+  ;;
+
+    *)
+  N=/etc/init.d/$NAME
+  # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
+  echo "Usage: $N {start|stop|restart|force-reload|status|force-stop|condrestart|try-restart}" >&2
+
+  exit 1
+  ;;
 esac
 
-exit $RETVAL
+exit 0
